### ISSUE TITLE
time-varying covariates and IV infusion lead to discordant results with NONMEM

### ISSUE THREAD

**Issue by levenc** [nlmixrdevelopment/RxODE#468] opened 2021-11-10 14:35 UTC
Hello,
I observe discordant results between RxODE and NONMEM (with the ADVAN13 routine) when simulating a model with time-varying covariates, and an IV infusion administration.
Unfortunately I don't have access to NONMEM, but I was able to run some tests thanks to the data made available by @FelicienLL in his repository.

The model involved is the run302 model from https://github.com/FelicienLL/mapbayr-CPTPSP-2021:

- The data can be found in "data"
- The NONMEM model in "nonmem code"
- The simulation results are in "nonmem output"

Here is the RxODE model I used:

```r
mod_run30x <- RxODE::RxODE({
  THETA_Cl = 4.0
  THETA_Vc = 70.0
  THETA_Ka = 1.0

  TVCl  = THETA_Cl*((BW/75)^1.5)*(0.75^SEX);
  TVVc  = THETA_Vc;
  TVKa  = THETA_Ka;

  Cl    = TVCl*exp(ETA_Cl);
  Vc    = TVVc*exp(ETA_Vc);
  Ka    = TVKa*exp(ETA_Ka);

  K20   = Cl/Vc;
  IPRED = centr/Vc;

  d/dt(depot)  = - Ka*depot;
  d/dt(centr)  =   Ka*depot - K20*centr;
  })
```

Simulation with the following command (specifying covariates_interpolation="nocb") gives conflicting results compared to NONMEM. 
```r
eta_302_1 <- c(ETA_Cl=0.398845969, ETA_Vc=0.0762201167, ETA_Ka=0)  # from NONMEM (MAP-EBE)

rx_302_1   <- RxODE::rxSolve(mod_run30x,eta_302_1,data_302_1,
                             covs_interpolation="nocb",
                             addDosing=TRUE)
```

On the other hand, the simulation of the same model, for the same patient, after oral administration (run301), agrees more closely with NONMEM.

This issue resembles the metrumresearchgroup/mrgsolve#741 issue encountered by mrgsolve. Here are the results with RxODE :
![time_varying_cov_infusion](https://user-images.githubusercontent.com/62027274/141116813-5fcfeaa6-435b-4629-af1f-4c97c81ae024.png)

```r
summary(simu_302[simu_302$solver == "NONMEM","IPRED"]-simu_302[simu_302$solver == "RxODE","IPRED"])
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
-3.6420 -1.0018 -0.2176 -0.3667  0.1929  3.9176 
```
When using oral route, the difference is much smaller.
```r
summary(simu_301[simu_301$solver == "NONMEM","IPRED"]-simu_301[simu_301$solver == "RxODE","IPRED"])
      Min.    1st Qu.     Median       Mean    3rd Qu.       Max. 
-6.837e-05 -1.870e-05 -4.892e-08 -1.416e-05  3.410e-06  7.872e-06 
```
Could this be related to the implementation of the "nocb" interpolation?
Thanks

**Comment by FelicienLL** [comment] 2021-11-10 15:40
Hi, 
Thanks for tagging me in this issue. I just simulated the corresponding dataset in mrgsolve: 
``` r
#> # A tibble: 12 x 11
#>       ID  time  evid   amt   cmt    ii  addl  rate   mdv    BW   SEX
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1     1   0       1 10000     2     0     0 10000     1    77     0
#>  2     1   1.5     0     0     2     0     0     0     0   113     0
#>  3     1   4.4     0     0     2     0     0     0     0    92     1
#>  4     1   7.1     0     0     2     0     0     0     0   132     0
#>  5     1  24.6     0     0     2     0     0     0     0   126     1
#>  6     1  72       1 10000     2     0     0 10000     1   128     1
#>  7     1  96       1 10000     2     0     0 10000     1    41     1
#>  8     1 120       1 10000     2     0     0 10000     1    56     1
#>  9     1 144       1 10000     2     0     0 10000     1    68     0
#> 10     1 168       1 10000     2     0     0 10000     1    45     0
#> 11     1 192       1 10000     2     0     0 10000     1    93     1
#> 12     1 216       1 10000     2     0     0 10000     1   126     1
```
and if I fix `ETA_Cl=0.398845969` and `ETA_Vc=0.0762201167` too I do not observe differences between the mrgsolve simulations and NONMEM:

``` r
#>    ID  time          MRG           NM
#> 1   1   0.0   0.00000000   0.00000000
#> 2   1   1.5 114.50244739 114.50244600
#> 3   1   4.4  90.69039240  90.69039150
#> 4   1   7.1  55.14948266  55.14948100
#> 5   1  24.6   5.78392388   5.78392375
#> 6   1  72.0   0.01112401   0.01112401
#> 7   1  96.0  75.46454595  75.46454410
#> 8   1 120.0  84.15780731  84.15780530
#> 9   1 144.0  43.12193343  43.12193320
#> 10  1 168.0  73.80668970  73.80668900
#> 11  1 192.0  29.79476713  29.79476750
#> 12  1 216.0   7.76462139   7.76462148
```

What TOL did you applied in your simulation in RxODE ? In NONMEM and mrgsolve, I used TOL8.

I share the same hypothesis than you: it is probably due to uncorrect updates of parameter values in the RxODE solver when parameters change from records to records, like we faced with mrgsolve in the issue you referenced. It appeared into specific circumstances, especially if drug were administered as infusions. Unfortunately, I could not tell you how to confirm it, nor how to fix it: is way too complex for me! Probably the mrgsolve issue you mentionned will be helpful enough? 
Anyway I'm curious of the result of this issue and it would be a pleasure to help if I can in any ways.

Best regards

Félicien

**Comment by mattfidler** [comment] 2021-11-10 19:34
Thank you for reporting the differences.  `mrgsolve` and `RxODE` use different methods internally for covariate extrapolation.  In general RxODE uses code taken from R's `approxfun`.  

They likely have other default solving values that are different

**Comment by mattfidler** [comment] 2021-11-10 20:31
I tried pulling out the dats from the zip file.  I plotted the data and it seems different than what is shown in this issue.  Perhaps I grabbed the wrong file or ID.  Can you provide a fully reproducible example, that is attach the data and scriot you used?

**Comment by levenc** [comment] 2021-11-10 20:44
Of course @mattfidler , sorry I didn't do it up front.

Here is the script I used:

```r
# RxODE model
mod_run30x <- RxODE::RxODE({
  THETA_Cl = 4.0
  THETA_Vc = 70.0
  THETA_Ka = 1.0

  TVCl  = THETA_Cl*((BW/75)^1.5)*(0.75^SEX);
  TVVc  = THETA_Vc;
  TVKa  = THETA_Ka;

  Cl    = TVCl*exp(ETA_Cl);
  Vc    = TVVc*exp(ETA_Vc);
  Ka    = TVKa*exp(ETA_Ka);

  K20   = Cl/Vc;
  IPRED = centr/Vc;

  d/dt(depot)  = - Ka*depot;
  d/dt(centr)  =   Ka*depot - K20*centr;
  })

# IV to centr
pat_302_1 <- data.frame(ID=1,
                        TIME=c(0.00000,1.50000,4.40000,7.10000,24.60000,72.00000,
                               96.00000,120.00000,144.00000,168.00000,192.00000,
                               216.00000),
                        EVID=c(1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1),
                        AMT=c(10000,0,0,0,0,10000,10000,10000,10000,10000,10000,10000),
                        CMT=2,
                        II=0,
                        ADDL=0,
                        RATE=c(10000,0,0,0,0,10000,10000,10000,10000,10000,10000,10000),
                        MDV=c(1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1),
                        DV=c(NA,107.26700,100.99500,54.05460,5.97081,NA,NA,NA,NA,NA,NA,NA),
                        BW=c(77,113,92,132,126,128,41,56,68,45,93,126),
                        SEX=c(0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1))


eta_302_1 <- c(ETA_Cl=0.398845969, ETA_Vc=0.0762201167, ETA_Ka=0)  # NONMEM

rx_302_1   <- RxODE::rxSolve(mod_run30x,eta_302_1,pat_302_1,
                             covs_interpolation="nocb",
                             addDosing=TRUE)

# Oral to depot
pat_301_1 <- data.frame(ID=1,
                        TIME=c(0.00000,1.50000,4.40000,7.10000,24.60000,72.00000,
                               96.00000,120.00000,144.00000,168.00000,192.00000,
                               216.00000),
                        EVID=c(1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1),
                        AMT=c(10000,0,0,0,0,10000,10000,10000,10000,10000,10000,10000),
                        CMT=c(1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1),
                        II=0,
                        ADDL=0,
                        MDV=c(1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1),
                        DV=c(NA,85.93470,105.34400,57.21840,6.32941,NA,NA,NA,NA,NA,NA,NA),
                        BW=c(77,113,92,132,126,128,41,56,68,45,93,126),
                        SEX=c(0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1))



eta_301_1 <- c(ETA_Cl=0.397632632, ETA_Vc=0.0632252546, ETA_Ka=-0.0815987631)  # NONMEM

rx_301_1   <- RxODE::rxSolve(mod_run30x,eta_301_1,pat_301_1,
                             covs_interpolation="nocb",
                             addDosing=TRUE)

# import NONMEM output
library(readr)
run301_tab <- read_table2("~/posologyr-pharmaceutics/issues/run301.tab.csv", skip = 1)
run302_tab <- read_table2("~/posologyr-pharmaceutics/issues/run302.tab.csv", skip = 1)

# plotting
run301_tab$time <- run301_tab$TIME
run302_tab$time <- run302_tab$TIME

simu_30x <- rbind(cbind(rx_301_1[,c("time","IPRED")],run="oral",solver="RxODE"),
                  cbind(rx_302_1[,c("time","IPRED")],run="IV",solver="RxODE"),
                  cbind(run301_tab[run301_tab$ID == 1,c("time","IPRED")],run="oral",
                        solver="NONMEM"),
                  cbind(run302_tab[run302_tab$ID == 1,c("time","IPRED")],run="IV",
                        solver="NONMEM"))

# summary of differences
# oral
summary(simu_30x[simu_30x$solver == "NONMEM" & simu_30x$run == "oral","IPRED"]-simu_30x[simu_30x$solver == "RxODE" & simu_30x$run == "oral","IPRED"])
# IV
summary(simu_30x[simu_30x$solver == "NONMEM" & simu_30x$run == "IV","IPRED"]-simu_30x[simu_30x$solver == "RxODE" & simu_30x$run == "IV","IPRED"])

``` 

Please find attached the output from NONMEM, kindly provided by Felicien:
[run301.tab.csv](https://github.com/nlmixrdevelopment/RxODE/files/7515765/run301.tab.csv)
[run302.tab.csv](https://github.com/nlmixrdevelopment/RxODE/files/7515767/run302.tab.csv)

@FelicienLL thanks for you input !

**Comment by mattfidler** [comment] 2021-11-11 02:25
Thanks, I can now reproduce this.

**Comment by mattfidler** [comment] 2021-11-11 03:50
This is a way to see what the covariate is doing in RxODE:

```r
    library(RxODE)
    # RxODE model
    mod_run30x <- RxODE({
      THETA_Cl = 4.0
      THETA_Vc = 70.0
      THETA_Ka = 1.0

      TVCl  = THETA_Cl*((BW/75)^1.5)*(0.75^SEX);
      TVVc  = THETA_Vc;
      TVKa  = THETA_Ka;

      Cl    = TVCl*exp(ETA_Cl);
      Vc    = TVVc*exp(ETA_Vc);
      Ka    = TVKa*exp(ETA_Ka);

      K20   = Cl/Vc;
      IPRED = centr/Vc;

      d/dt(depot)  = - Ka*depot;
      d/dt(centr)  =   Ka*depot - K20*centr;
      printf("%f\t%f\n", time, BW)
    })

    # IV to centr
    pat_302_1 <- data.frame(ID=1,
                            TIME=c(0.00000,1.50000,4.40000,7.10000,24.60000,72.00000,
                                   96.00000,120.00000,144.00000,168.00000,192.00000,
                                   216.00000),
                            EVID=c(1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1),
                            AMT=c(10000,0,0,0,0,10000,10000,10000,10000,10000,10000,10000),
                            CMT=2,
                            II=0,
                            ADDL=0,
                            RATE=c(10000,0,0,0,0,10000,10000,10000,10000,10000,10000,10000),
                            MDV=c(1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1),
                            DV=c(NA,107.26700,100.99500,54.05460,5.97081,NA,NA,NA,NA,NA,NA,NA),
                            BW=c(77,113,92,132,126,128,41,56,68,45,93,126),
                            SEX=c(0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1))


    eta_302_1 <- c(ETA_Cl=0.398845969, ETA_Vc=0.0762201167, ETA_Ka=0)  # NONMEM

    sink("rx302.1.tab")
    cat("time\tBW\n")
    rx_302_1   <- RxODE::rxSolve(mod_run30x,eta_302_1,pat_302_1,
                                 covs_interpolation="nocb",
                                 addDosing=TRUE)
    sink()

    f2 <- read.table("/tmp/rx302.1.tab", header=TRUE)

    ggplot(f2, aes(time, BW)) + geom_line() +
      geom_vline(xintercept=c(0, 72, 96, 120, 144, 168, 192, 216), col="red") +
      geom_vline(xintercept=c(0, 72, 96, 120, 144, 168, 192, 216) + 1, col="blue")
```

![issue-409](https://user-images.githubusercontent.com/514778/141233553-513d382d-c1c8-4d35-98f5-52e954cdfd97.png)
![issue-468](https://user-images.githubusercontent.com/514778/141233707-5ef01f69-32fb-4db3-8d24-df84d353d512.png)

I believe this means that the imputation is different because the covariate is copied from the initial record to when the infusion is turned off, but this covariate should be treated as missing instead

**Comment by mattfidler** [comment] 2021-11-11 04:22
This is the translated dataset

``` r
    library(RxODE)
#> detected new version of RxODE, cleaning cache
#> RxODE 1.1.2 using 4 threads (see ?getRxThreads)
    # RxODE model
    mod_run30x <- RxODE({
      THETA_Cl = 4.0
      THETA_Vc = 70.0
      THETA_Ka = 1.0

      TVCl  = THETA_Cl*((BW/75)^1.5)*(0.75^SEX);
      TVVc  = THETA_Vc;
      TVKa  = THETA_Ka;

      Cl    = TVCl*exp(ETA_Cl);
      Vc    = TVVc*exp(ETA_Vc);
      Ka    = TVKa*exp(ETA_Ka);

      K20   = Cl/Vc;
      IPRED = centr/Vc;

      d/dt(depot)  = - Ka*depot;
      d/dt(centr)  =   Ka*depot - K20*centr;
      printf("%f\t%f\n", time, BW)
    })
#> → creating RxODE include directory
#> → getting R compile options
#> → precompiling headers
#> ✔ done

    # IV to centr
    pat_302_1 <- data.frame(ID=1,
                            TIME=c(0.00000,1.50000,4.40000,7.10000,24.60000,72.00000,
                                   96.00000,120.00000,144.00000,168.00000,192.00000,
                                   216.00000),
                            EVID=c(1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1),
                            AMT=c(10000,0,0,0,0,10000,10000,10000,10000,10000,10000,10000),
                            CMT=2,
                            II=0,
                            ADDL=0,
                            RATE=c(10000,0,0,0,0,10000,10000,10000,10000,10000,10000,10000),
                            MDV=c(1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1),
                            DV=c(NA,107.26700,100.99500,54.05460,5.97081,NA,NA,NA,NA,NA,NA,NA),
                            BW=c(77,113,92,132,126,128,41,56,68,45,93,126),
                            SEX=c(0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1))

    etTrans(pat_302_1, mod_run30x)
#>   ID TIME  EVID    AMT II        DV SEX  BW
#> 1  1  0.0 10201  10000  0        NA   0  77
#> 2  1  1.0 10201 -10000  0        NA  NA  NA
#> 3  1  1.5     0     NA  0 107.26700   0 113
#> 4  1  4.4     0     NA  0 100.99500   1  92
#> 5  1  7.1     0     NA  0  54.05460   0 132
#> 6  1 24.6     0     NA  0   5.97081   1 126
#> 
#> Covariates (non time-varying):
#>   ID
#> 1  1
#> 
#> Compartment translation:
#> [1] Compartment Number
#> <0 rows> (or 0-length row.names)
```

<sup>Created on 2021-11-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by mattfidler** [comment] 2021-11-11 05:04
Should be fixed in the pull  request #469 

```r
    # RxODE model
    mod_run30x <- RxODE({
      THETA_Cl = 4.0
      THETA_Vc = 70.0
      THETA_Ka = 1.0

      TVCl  = THETA_Cl*((BW/75)^1.5)*(0.75^SEX);
      TVVc  = THETA_Vc;
      TVKa  = THETA_Ka;

      Cl    = TVCl*exp(ETA_Cl);
      Vc    = TVVc*exp(ETA_Vc);
      Ka    = TVKa*exp(ETA_Ka);

      K20   = Cl/Vc;
      IPRED = centr/Vc;

      d/dt(depot)  = - Ka*depot;
      d/dt(centr)  =   Ka*depot - K20*centr;
    })

    # IV to centr
    pat_302_1 <- data.frame(ID=1,
                            TIME=c(0.00000,1.50000,4.40000,7.10000,24.60000,72.00000,
                                   96.00000,120.00000,144.00000,168.00000,192.00000,
                                   216.00000),
                            EVID=c(1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1),
                            AMT=c(10000,0,0,0,0,10000,10000,10000,10000,10000,10000,10000),
                            CMT=2,
                            II=0,
                            ADDL=0,
                            RATE=c(10000,0,0,0,0,10000,10000,10000,10000,10000,10000,10000),
                            MDV=c(1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1),
                            DV=c(NA,107.26700,100.99500,54.05460,5.97081,NA,NA,NA,NA,NA,NA,NA),
                            BW=c(77,113,92,132,126,128,41,56,68,45,93,126),
                            SEX=c(0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1))

    eta_302_1 <- c(ETA_Cl=0.398845969, ETA_Vc=0.0762201167, ETA_Ka=0)  # NONMEM

    rx_302_1   <- RxODE::rxSolve(mod_run30x,eta_302_1,pat_302_1,
                                 covs_interpolation="nocb",
                                 addDosing=TRUE)

    # Oral to depot
    pat_301_1 <- data.frame(ID=1,
                            TIME=c(0.00000,1.50000,4.40000,7.10000,24.60000,72.00000,
                                   96.00000,120.00000,144.00000,168.00000,192.00000,
                                   216.00000),
                            EVID=c(1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1),
                            AMT=c(10000,0,0,0,0,10000,10000,10000,10000,10000,10000,10000),
                            CMT=c(1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1),
                            II=0,
                            ADDL=0,
                            MDV=c(1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1),
                            DV=c(NA,85.93470,105.34400,57.21840,6.32941,NA,NA,NA,NA,NA,NA,NA),
                            BW=c(77,113,92,132,126,128,41,56,68,45,93,126),
                            SEX=c(0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1))



    eta_301_1 <- c(ETA_Cl=0.397632632, ETA_Vc=0.0632252546, ETA_Ka=-0.0815987631)  # NONMEM

    rx_301_1   <- RxODE::rxSolve(mod_run30x,eta_301_1,pat_301_1,
                                 covs_interpolation="nocb",
                                 addDosing=TRUE)

    # import NONMEM output
    lst <- qs::qread("test-issue-468.qs")

    run301_tab <- as.data.frame(lst[[1]])
    run302_tab <- as.data.frame(lst[[2]])

    # plotting
    run301_tab$time <- run301_tab$TIME
    run302_tab$time <- run302_tab$TIME


    simu_30x <- rbind(cbind(rx_301_1[,c("time","IPRED")],run="oral",solver="RxODE"),
                      cbind(rx_302_1[,c("time","IPRED")],run="IV",solver="RxODE"),
                      cbind(run301_tab[run301_tab$ID == 1,c("time","IPRED")],run="oral",
                            solver="NONMEM"),
                      cbind(run302_tab[run302_tab$ID == 1,c("time","IPRED")],run="IV",
                            solver="NONMEM"))

library(ggplot2)
ggplot(simu_30x,aes(time,IPRED,color=solver)) + geom_line() + facet_grid(cols = vars(run)) + theme_bw()
```
 
![issue-468](https://user-images.githubusercontent.com/514778/141240485-68a90a56-82b4-43d9-bfd1-f4af81c7c838.png)

**Comment by mattfidler** [comment] 2021-11-11 12:46
This is now in the master branch you can use the development version by:

```r
remotes::install_github("nlmixrdevelopment/RxODE")
```

**Comment by mattfidler** [comment] 2021-11-11 16:17
Let me know if you still have any problems @levenc.  Thanks @FelicienLL for your input.

**Comment by levenc** [comment] 2021-11-11 16:17
Thank you a lot ! This is really informative, and of course very useful. After installing the development version, I can confirm that it works now.

I did a last test with a different administration plan (same files, subject 3), and the difference I saw yesterday also disappeared after the patch.

```r
# IV to centr
pat_302_3 <- data.frame(ID=3,
                        TIME=c(0.0,72.0,96.0,120.0,144.0,168.0,192.0,215.0,216.0,
                               216.0,221.0,222.6),
                        EVID=c(1,1,1,1,1,1,1,0,0,1,0,0),
                        AMT=c(10000,10000,10000,10000,10000,10000,10000,0,0,10000,0,0),
                        CMT=2,
                        II=0,
                        ADDL=0,
                        RATE=c(10000,10000,10000,10000,10000,10000,10000,0,0,10000,0,0),
                        MDV=c(1,1,1,1,1,1,1,0,0,1,0,0),
                        DV=c(NA,NA,NA,NA,NA,NA,NA,3.86656,3.96808,0.00000,98.24300,
                             76.08230),
                        BW=c(101,114,69,131,133,46,110,99,119,118,77,104),
                        SEX=c(1,0,1,1,0,1,1,1,1,1,1,0))


eta_302_3 <- c(ETA_Cl=0.746690095, ETA_Vc=-0.17818529, ETA_Ka=0)  # NONMEM

rx_302_3   <- RxODE::rxSolve(mod_run30x,eta_302_3,pat_302_3,
                             covs_interpolation="nocb",
                             addDosing=TRUE)

# Oral to depot
pat_301_3 <- data.frame(ID=3,
                        TIME=c(0.0,72.0,96.0,120.0,144.0,168.0,192.0,215.0,216.0,
                               216.0,221.0,222.6),
                        EVID=c(1,1,1,1,1,1,1,0,0,1,0,0),
                        AMT=c(10000,10000,10000,10000,10000,10000,10000,0,0,10000,0,0),
                        CMT=c(1,1,1,1,1,1,1,2,2,1,2,2),
                        II=0,
                        ADDL=0,
                        MDV=c(1,1,1,1,1,1,1,0,0,1,0,0),
                        DV=c(NA,NA,NA,NA,NA,NA,NA,4.27400,4.38622,0.00000,103.55300,
                             81.06530),
                        BW=c(101,114,69,131,133,46,110,99,119,118,77,104),
                        SEX=c(1,0,1,1,0,1,1,1,1,1,1,0))



eta_301_3 <- c(ETA_Cl=0.740874254, ETA_Vc=-0.180011473, ETA_Ka=0.0587246819)  # NONMEM

rx_301_3   <- RxODE::rxSolve(mod_run30x,eta_301_3,pat_301_3,
                             covs_interpolation="nocb",
                             addDosing=TRUE)

# plotting
run301_tab$time <- run301_tab$TIME
run302_tab$time <- run302_tab$TIME

simu_30x_3 <- rbind(cbind(rx_301_3[,c("time","IPRED")],run="oral",solver="RxODE"),
                  cbind(rx_302_3[,c("time","IPRED")],run="IV",solver="RxODE"),
                  cbind(run301_tab[run301_tab$ID == 3,c("time","IPRED")],run="oral",
                        solver="NONMEM"),
                  cbind(run302_tab[run302_tab$ID == 3,c("time","IPRED")],run="IV",
                        solver="NONMEM"))

ggplot2::ggplot(simu_30x_3,aes(time,IPRED,color=solver)) + geom_line() + facet_grid(cols = vars(run)) + theme_bw()

```
Before  #469:
![time_varying_cov_infusion_3](https://user-images.githubusercontent.com/62027274/141331172-8875f3fa-9d71-4132-ace2-eb39dde47e27.png)
After updating to the development version:
![time_varying_cov_infusion_3_fixed](https://user-images.githubusercontent.com/62027274/141331208-9631eadb-b37c-4c92-9906-c62e2e7601b7.png)

**Closed** 2021-11-11 16:16 UTC

**Comment by mattfidler** [comment] 2021-11-11 16:18
Great @levenc 

I am glad to hear that.

**Comment by FelicienLL** [comment] 2021-11-12 08:35
Thank you for the explanations @mattfidler, and glad you managed to fix it.
Have a great day
Félicien.
